#include "base.h"
#include "tpos.h"
#include "zpos.h"

#ifndef __GENERAL_UTIL_H__
#define __GENERAL_UTIL_H__

message_define *match_priv_stru(const char *msg_type,GLOB_DEF * gl_def);
extern int iso_unpack(char *src_buf,int src_len,glob_msg_stru *pub_data_stru);
extern int tpos_unpack(char *src_buf,int src_len,glob_msg_stru *pub_data_stru);
extern int xml_unpack(const char *msg_type, message_define *priv_def,char *src_buf,int src_len,glob_msg_stru *pub_data_stru);
extern int iso_pack(glob_msg_stru *pub_data_stru,char *buf,int size);
extern int xml_pack(const char *msg_type, message_define *priv_def, glob_msg_stru *pub_data_stru, char *buf);
extern int tpos_pack(glob_msg_stru *pub_data_stru,char *buf,int size);
int add_pub_field(glob_msg_stru * pub_data_stru,short id,const char *msg_type,int data_len,const char *data,char from );
int update_pub_field(glob_msg_stru * pub_data_stru,short id,const char * msg_type,int data_len,const char *data,char from );
int del_pub_field(glob_msg_stru * pub_data_stru,short id,const char *msg_type,char from );
int _get_field_data_safe(glob_msg_stru *pub_data_stru,short field_id,const char *msg_type,char *data, char flag,int size);
int get_field_data_safe(glob_msg_stru *pub_data_stru,int field_id,const char *msg_type,char *data,int size);
int get_in_msg_type(glob_msg_stru *pub_data_stru,char *msg_type,int size);
field_define* get_defstru_of_name(const char *name,const message_define *priv_def);
field_define* get_defstru_of_id(short id,const message_define *priv_def);
int set_result_code(glob_msg_stru *pub_data_stru, char *ret_code);
int is_open_of_out_insti (glob_msg_stru *pub_data_stru);
int check_route_insti(glob_msg_stru *pub_data_stru);
int IsReady(const char *pcaName);
char *my_split(char *s1, const char s2,char *s3, int size_s3);
int GetFolderIdByName(const char *pcaBankName);
int get_pub_field_id(const char *msg_type,const char *name);
void set_in_cry_flag(glob_msg_stru *pub_data_stru, int flag);
void set_out_cry_flag(glob_msg_stru *pub_data_stru, int flag);
void rtrim( char * str);
void rtrim_c( char * str, char c);
int del_route_set(glob_msg_stru *pub_data_stru,const char *msg_type,
                  const char *field_name);
int add_route_set(glob_msg_stru *pub_data_stru, const char *msg_type,
                  const char *field_name, int from);
void void_proc(glob_msg_stru *pub_data_stru);
int folder_to_insti_code(char * fold_name,char *insti_code,int size);
int GenMacSM(char *key_index, char *key_data, char *macData, int length, char *mac_out);
int GenMac(char *key_index, char *key_data, char *macData, int length, char *mac_out);
int get_systime(char *para, short fldid, glob_msg_stru *pub_data_stru);
int set_field_service_entry(char *para, short fldid, glob_msg_stru *pub_data_stru);
int make_data(char *para, short fldid, glob_msg_stru *pub_data_stru);
int get_msg_data(char *para, short fldid, glob_msg_stru *pub_data_stru);
int get_db_data(char *para, short fldid, glob_msg_stru *pub_data_stru);
int get_db_data_fill(char *para, short fldid, glob_msg_stru *pub_data_stru);
int get_org_trans_info(char *para, short fldid, glob_msg_stru *pub_data_stru);
int mac_calc_all_3des(char *para, char *buf, int bufLen, char *mac, glob_msg_stru *pub_data_stru, int flag);
int mac_calc_all_des(char *para, char *buf, int bufLen, char *mac, glob_msg_stru *pub_data_stru, int flag);
int pin_change(char *para, short fldid, glob_msg_stru *pub_data_stru);
int write_voidtrans_to_fold(timeout_stru *table);
int iso_cbc_str(char *para, char *macBuf, int *mac_len, char * field_name, const message_define *p_def, const char *buf, glob_msg_stru *pub_data_stru, int len_type);

int iso_tl_head_proc ( char *buf ,int start, int len);
int CalcFee(char *caFeeType, char *caFee, int amount, char *caKee);
void print_field_data(glob_msg_stru *pub_data_stru, char *fileName, int fileline, int d, int fieldid, char *fieldName, char *msg_type);
int get_msg_data_fill(char *para, short fldid, glob_msg_stru *pub_data_stru);
int get_msg_data_tlvfill(char *para, short fldid, glob_msg_stru *pub_data_stru);
int get_data_standard(char *para, short fldid, glob_msg_stru *pub_data_stru);
int set_service_code(char *para, short fldid, glob_msg_stru *pub_data_stru);
int set_field_60(char *para, short fldid, glob_msg_stru *pub_data_stru);
int change_db_data(char *para, short fldid, glob_msg_stru *pub_data_stru);
int con_del_fld48(char *para, short fldid, glob_msg_stru *pub_data_stru);
int check_amount(char *para, short fldid, glob_msg_stru *pub_data_stru);
int cancle_trans_specific(char *para, short fldid, glob_msg_stru *pub_data_stru);
void asc_to_bcd ( unsigned char* bcd_buf , unsigned char* ascii_buf , int conv_len ,unsigned char type );
void bcd_to_asc (unsigned char* ascii_buf ,unsigned char* bcd_buf , int conv_len ,unsigned char type );
int GenMac3Des(char *key_index, char *key_data, char *macData, int length, char *mac_out);
int card_info_check(char *para, short flag, glob_msg_stru *pub_data_stru);
int trans_control(char *para, short flag, glob_msg_stru *pub_data_stru);
int iso_check_mac_all_des(char *para, short flag, glob_msg_stru *pub_data_stru);
int iso_check_mac_all_3des(char *para, short flag, glob_msg_stru *pub_data_stru);
int iso_check_mac_cbc_3des(char *para, short flag, glob_msg_stru *pub_data_stru);
int _tpos_check_terminal(char *para, short flag, glob_msg_stru *pub_data_stru);
int _tpos_check_mac(char *para, short flag, glob_msg_stru *pub_data_stru);
int is_valid_cardbin(char *para, short fldid, glob_msg_stru *pub_data_stru);
int tpos_get_last_addidata(char *para, short flag, glob_msg_stru * pub_data_stru);
int get_end_trans(char *para, short flag, glob_msg_stru *pub_data_stru);
int trans_cancle(char *para, short flag, glob_msg_stru *pub_data_stru);
int tpos_trans_cancle(char *para, short flag, glob_msg_stru *pub_data_stru);
int tpos_trans_refund(char *para, short flag, glob_msg_stru *pub_data_stru);
int calculate_fee(char *para, short flag, glob_msg_stru *pub_data_stru);
int check_expenses_result(char *para, short fldid, glob_msg_stru *pub_data_stru);
int tpos_check_expenses_result(char *para, short flag, glob_msg_stru *pub_data_stru);
int tpos_discount_result(char *para, short flag, glob_msg_stru *pub_data_stru);
int tpos_field_pre_conv(char *para, short flag, glob_msg_stru *pub_data_stru);
int verify_passwd(char *para, short fldid, glob_msg_stru *pub_data_stru);
int is_valid_cardbin(char *para, short fldid, glob_msg_stru *pub_data_stru);
int tpos_check_mac(glob_msg_stru * pub_data_stru);
int tpos_check_terminal(glob_msg_stru * pub_data_stru);
int tpos_check_prog_ver(glob_msg_stru * pub_data_stru);
int tpos_check_menu_ver(glob_msg_stru * pub_data_stru);
int reversed_replay(glob_msg_stru * pub_data_stru);
int find_replay(glob_msg_stru * pub_data_stru);
int notify_replay(glob_msg_stru * pub_data_stru);
int sign_m_p_32(glob_msg_stru * pub_data_stru);
int result_query_tl(glob_msg_stru * pub_data_stru);
int result_query_hnyl(glob_msg_stru * pub_data_stru);
int tpos_login(glob_msg_stru * pub_data_stru);
int tpos_download_para(glob_msg_stru * pub_data_stru);
int tpos_link_test(glob_msg_stru * pub_data_stru);
int tpos_reversed(glob_msg_stru * pub_data_stru);
int end_trans(glob_msg_stru *pub_data_stru);
int app_reversed(glob_msg_stru * pub_data_stru);
int sign_request(glob_msg_stru * pub_data_stru);
int key_reset(glob_msg_stru * pub_data_stru);
int bill_fee_find(glob_msg_stru *pub_data_stru);
int query_expenses(glob_msg_stru * pub_data_stru);
int tpos_query_expenses(glob_msg_stru *pub_data_stru);
int save_tc_value(glob_msg_stru * pub_data_stru);
int insti_login(glob_msg_stru * pub_data_stru);
int tpos_settle(glob_msg_stru * pub_data_stru);
int bill_pay(glob_msg_stru *pub_data_stru);
int tpos_gen_field_conver(char *para, short fldid, glob_msg_stru *pub_data_stru);
int get_seq(char *para, short fldid, glob_msg_stru *pub_data_stru);
int get_ref(char *para, short fldid, glob_msg_stru *pub_data_stru);
int get_default(char *para, short fldid, glob_msg_stru *pub_data_stru);
int print_format(char *para, short fldid, glob_msg_stru *pub_data_stru);
int ic55_ret(char *para, short fldid, glob_msg_stru *pub_data_stru);
int save_timeout(char *para, short fldid, glob_msg_stru *pub_data_stru);
int read_timeout(char *para, short fldid, glob_msg_stru *pub_data_stru);
int show_format(char *para, short fldid, glob_msg_stru *pub_data_stru);
int set_ctrl_info(char *para, short fldid, glob_msg_stru *pub_data_stru);
int electricity_payment_48(char *para, short fldid, glob_msg_stru *pub_data_stru);
int format_echo_input(char *para, short fldid, glob_msg_stru *pub_data_stru);
int specific_business_handle(char *para, short fldid, glob_msg_stru *pub_data_stru);
int general_buisiness_handle(char *para, short fldid, glob_msg_stru *pub_data_stru);
int mac_calc_cbc_iso_3des(char *para, char *src_buf, int src_len, char *mac, glob_msg_stru *pub_data_stru, int flag);
int check_replay_cd(char *para, short flag, glob_msg_stru *pub_data_stru);
int _tpos_get_work_key( glob_msg_stru *pub_data_stru);
int update_db_pay_ret(char *para, short flag, glob_msg_stru *pub_data_stru);
int update_db_pay_app(char *para, short flag, glob_msg_stru *pub_data_stru);
int update_db_app_ret(char *para, short flag, glob_msg_stru *pub_data_stru);
int update_db_app_pay(char *para, short flag, glob_msg_stru *pub_data_stru);
int fdc_notify(char *para, char *inst_code,glob_msg_stru *pub_data_stru);
int insert_expenses (char *para, char *inst_code,glob_msg_stru *pub_data_stru);
int check_cardbin(char *para, short fldid, glob_msg_stru *pub_data_stru);
int check_cnt_mer(char *para, short fldid, glob_msg_stru *pub_data_stru);
int check_valid_date(char *para, short fldid, glob_msg_stru *pub_data_stru);
int check_cntuser_curdate(char *para, short fldid, glob_msg_stru *pub_data_stru);

int get_insti_code(glob_msg_stru *pub_data_stru, char *field_id);
int err_set_msg(glob_msg_stru *pub_data_stru);
int genrate_field_conver_handle(char *handle, char *para, short fldid, glob_msg_stru *pub_data_stru);
int priv_field_conver_handle(char *handle, char *para, short fldid, glob_msg_stru *pub_data_stru);
int special_business(char *handle, char *para, short fldid, glob_msg_stru *pub_data_stru);
void strcpy_safe(char *des, char *src, int len);
field_define* get_priv_field_def(const char *name,short *id,const message_define *priv_def);

int discnt_check_list(glob_msg_stru *pub_data_stru,char *check_list);
int cacl_discount_1(char *amount,char *para,glob_msg_stru *pub_data_stru);
int conver_data(glob_msg_stru * pub_data_stru, int flag);
int get_route_insti_code(glob_msg_stru * pub_data_stru);
int load_db_trans_info(glob_msg_stru *pub_data_stru);
int reply_acq(glob_msg_stru *pub_data_stru);
field_define* get_priv_field_def_for_id(short id,const message_define *priv_def);
int set_cry_flag(glob_msg_stru *pub_data_stru, int cry_flag);
int tpos_update_work_key(char *psam, char *pin_key,char *mac_key,char *cd_key);
int priv_field_conver(glob_msg_stru * pub_data_stru);
void init_pub_data_stru(glob_msg_stru * pub_data_stru);
int is_gm_type(const char * src_type);
int request_msg_proc(glob_msg_stru *pub_data_stru);
int response_msg_proc(glob_msg_stru *pub_data_stru);
int get_route_trans_set(glob_msg_stru * pub_data_stru);
int pack_msg(glob_msg_stru *pub_data_stru,char *buf,int size);
int unpack_msg(char *src_buf,int src_len,glob_msg_stru *pub_data_stru);
int pack_key(char *keyBuf, int keySize, char *keySet, glob_msg_stru *pub_data_stru, char *msg_type, int flag, char d);
int E2E(char *acqinst, char *acqerrcode, char *objerrcode, int size);
int get_trans_info_from_insticode(glob_msg_stru * pub_data_stru);
int get_trans_info_from_msg(glob_msg_stru * pub_data_stru);
int get_route_insti_info(glob_msg_stru * pub_data_stru);
int get_terminal_class(char *t_class, glob_msg_stru *pub_data_stru);
int get_route_no(char *route_no, glob_msg_stru * pub_data_stru);
int update_db_voidflag(tl_trans_log_def *log, char flag, char *ret_code);
int GetTimeoutTrans(glob_msg_stru *pub_data_stru);
int timeout_handle(glob_msg_stru *pub_data_stru);
int confirm_app_type(glob_msg_stru *pub_data_stru);
int direct_respose(glob_msg_stru *pub_data_stru);
int get_default_field(glob_msg_stru *pub_data_stru);
int check_app_limit(glob_msg_stru *pub_data_stru);
int get_route_trans_info(glob_msg_stru * pub_data_stru);
int check_direct_limit(glob_msg_stru *pub_data_stru);
int get_direct_name(const char *msg_type,const char *app_type,char *name,int size);
int end_proc(glob_msg_stru *pub_data_stru);
int check_and_match(glob_msg_stru *pub_data_stru);
int trans_end_notify(glob_msg_stru *pub_data_stru);
int save_addidata(glob_msg_stru *pub_data_stru, int data_flag);
int get_iso_para(const char *msg_type, int *head_flag, int *head_len, int *msgid_flag, int *bitmap_flag, int *len_type);
int mac_calc_handle(int flag, glob_msg_stru * pub_data_stru, char *mac, char *buf, int bufLen);
int head_proc(char *msg_type,char *buf, int start,int len);
int is_permit_update_menu( char * msg_type,char * func_code);
int tpos_add_result_disp(glob_msg_stru *pub_data_stru);
int tpos_conver_priv_field_code(const field_define *p_fld,const char *func_code,char *data);
int tpos_get_work_key(const char *psam,char *pin_indx,char *mac_indx,char * data_indx,char* pin_key,char *mac_key,char * data_key);
int get_tpos_info(char *psam,struct TPOS_TERM_INFO *terminfo);
int tpos_reset_download(char *psam, char flag);
int get_ic_data(char *buf, int bSize, char *node_set, int *cnt);
int select_translog(tl_trans_log_def *pTransLog);
int get_advert_inf(glob_msg_stru *pub_data_stru,char *term_id,char *advert_head, size_t head_size,
                   char *advert_inf, size_t inf_size, char *advert_tail, size_t tail_size);
int get_aid_data(char *buf, int bSize, char *node_set, int *last_ic_para_step, int *cnt);
int db_save_set_ic( char *node_set,int step,char *psam, int flag);
int get_pubkey_data(char *buf, int bSize, char *node_set, int *last_ic_para_step, int *cnt);
int get_term_discount_info(DISCNT_INFO *discnt_info);
int  fold_locate_folder(const char *folder_name);
int confirm_trans_type(glob_msg_stru * pub_data_stru);
int GetBank(char *cardNo, char *bankCode, size_t bank_code_size, char *cardType, size_t card_type_size);
int get_term_trans_control(char *creditflag, int *credit_card, int *credit_d_a, int *credit_d_c, 
														int *debit_card, int *debit_d_a, int *debit_d_c, glob_msg_stru *pub_data_stru);
int AddUpTrans(char *cardno, int *amount, int *count, char *app_type, int flag);
int db_to_pub_daba(glob_msg_stru * pub_data_stru, tl_trans_log_def *pTransLog);
int insert_timeout_table(glob_msg_stru *pub_data_stru, int flag);
int update_db_result_pay(tl_trans_log_def *log,char *ret_code);
int get_key_info(char *insti_code, char *mac_tek_index, size_t mac_tek_index_size, char *mac_tmk_key, size_t mac_tmk_key_size,
                 char *pin_tek_index, size_t pin_tek_index_size, char *pin_tmk_key, size_t pin_tmk_key_size);
int GetSpecificBusinessPara(char *in_add_data, char *out_add_data, glob_msg_stru * pub_data_stru);
int GetGeneralBusinessPara(glob_msg_stru * pub_data_stru,char *para);
int check_card_limit(char *card_no,char *iss_insti, char *flag);
int genrate_field_conver_handle(char *handle, char *para, short fldid, glob_msg_stru *pub_data_stru);
int special_business_handle(glob_msg_stru * pub_data_stru);
int route_proc(glob_msg_stru *pub_data_stru);
int get_terminal_route(glob_msg_stru * pub_data_stru);
int get_easy_route(glob_msg_stru * pub_data_stru);
int get_bin_route(glob_msg_stru * pub_data_stru);
int db_genrate_query(glob_msg_stru *pub_data_stru);
int genrate_field_conver(glob_msg_stru *pub_data_stru);
int zpos_gen_work_key(glob_msg_stru *pub_data_stru,const char *psam);
int count_aid(int step);
int count_pubkey( int step);
int empty_tmp_para( char *psam);
int insti_gen_work_key(glob_msg_stru *pub_data_stru);
int tc_send(char *para, short flag, glob_msg_stru *pub_data_stru);
int end_trans_print(glob_msg_stru *pub_data_stru);
int format_msg_data(char *data, int data_len, char *format, int len_start, 
										int len_end, char *format_data, int size);
int print_formater(char *para, short fldid, glob_msg_stru *pub_data_stru);
int show_formater(char *para, short fldid, glob_msg_stru *pub_data_stru);
int get_data_from(char *para, short fldid, glob_msg_stru *pub_data_stru);
#endif
